function logP2_P1 = logMapHypersphere (p1, p2)
  
% p1 is a column vector: (dimension,1)
% p2 is a matrix: (dimension, numOfPoints)

innerProduct = max (-1, min (1, p2' * p1));
  
logP2_P1 ...
    =  ( p2 - p1 * innerProduct' ) ...
    .* ( ones (size (p2,1), 1, 'single') * ...
         ( acos (innerProduct) ./ ...
           max (1e-10, sqrt (1 - innerProduct.^2)) ...
           )' ...
         );

return